name: Generate issue label badges

on:
  label:
    types: [created, deleted, edited]

jobs:
  test_ruby_func:
    runs-on: ubuntu-latest
    name: A job to run funcs
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run funcs
      uses: gitx-io/ActionServerless@master
      with:
        filepath: ./issue-label-badges
    - name: Git commit
      run: |
        # git commit if there's any change
        if test -n "$(git status --porcelain 2>/dev/null)"; then
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add .
            git commit -m "Add changes"
            git push origin ${GITHUB_REF##*/}
        fi
